name: SortTV for GHCR

on:
  push:
    branches:
      - "main"

jobs:
  build_and_pubish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username eUwSqBTm --password ${{ secrets.DOCKERHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/euwsqbtm/sorttv:latest
          docker push ghcr.io/euwsqbtm/sorttv:latest
